Repository 2-FavoritePhoto-2/2-FavoritePhoto-2-BE, pull requests merged in 2024-12, with the labels that each got.

#44 [강명곤]Feature/get pointlogs
  src/controllers/points.controller.ts
  src/repositories/points.repository.ts
  src/repositories/user.repository.ts
  src/routes/points.route.ts
  src/services/points.service.ts
  src/utils/errors.ts
Labels: 완성

#47 [강명곤]Refactor: Replace try-catch with asyncHandler in Exchange
  src/controllers/exchange.controller.ts
  src/routes/exchange.route.ts
Labels: 완성

#46 [이동훈] Refactor: Use async-handler for delete try-catch
  src/controllers/user.controller.ts
Labels: 완성

#48 [김영은] Feat: Add swagger example
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app.ts
  src/swagger/swagger.yaml
  tsconfig.json
Labels: 진행중

#50 [강명곤]Feat: Apply exchange structs
  prisma/structs.ts
  src/controllers/exchange.controller.ts
Labels: 완성

#51 [강명곤]Fix: add approved exchange validation
  http/exchange.http
  package-lock.json
  src/services/exchange.service.ts
Labels: 완성

#52 [이동훈] Refactor: Create card struct
  src/controllers/user.controller.ts
  src/services/user.service.ts
Labels: 완성

#62 [강명곤]Chore: Fix some mockdata image
  mock/mock.ts
Labels: 완성

#66 [강명곤]Fix:pointlog period filter
  src/app.ts
  src/services/points.service.ts
Labels: 완성

#69 [강명곤] Docs: Update README with detailed exchange and points functionality
  README.md
Labels: 완성

#73 production deploy
  README.md
  http/example.http
  http/user.http
  mock/mock.ts
  prisma/migrations/20241206011207_init/migration.sql
  src/app.ts
  src/containers/example.container.ts
  src/controllers/auth.controller.ts
  src/controllers/example.controller.ts
  src/repositories/example.repository.ts
  src/repositories/exchange.repository.ts
  src/repositories/shop.repository.ts
  src/repositories/user.repository.ts
  src/routes/example.route.ts
  src/routes/index.route.ts
  src/services/example.service.ts
  src/services/exchange.service.ts
  src/services/points.service.ts
  src/services/shop.service.ts
  src/services/user.service.ts
  src/swagger/swagger.yaml
  src/utils/errorHandler.ts
  src/utils/errors.ts
Labels: 배포

#77 dev to main
  .github/workflows/slackAlarm.yml
  README.md
  http/user.http
  src/app.ts
  src/controllers/auth.controller.ts
  src/controllers/exchange.controller.ts
  src/controllers/shop.controller.ts
  src/controllers/user.controller.ts
  src/middlewares/asyncHandler.ts
  src/middlewares/errorHandler.ts
  src/middlewares/verifyAuth.ts
  src/routes/auth.route.ts
  src/routes/exchange.route.ts
  src/routes/notification.route.ts
  src/routes/points.route.ts
  src/routes/shop.route.ts
  src/routes/user.route.ts
  src/services/auth.service.ts
  src/services/shop.service.ts
  src/services/user.service.ts
  src/utils/S3/s3.ts
  src/utils/S3/upload.ts
  src/utils/bcrypt.ts
  src/utils/errorHandler.ts
  src/utils/structs.ts
  src/utils/upload.ts
Labels: 배포
